### ISSUE TITLE
Settle on a new name

### ISSUE THREAD

**Issue by shazow** [shazow/callthis#2]
Not sure I love callthis.eth

😐

**Comment by shazow** [comment]
Some ideas here: https://warpcast.com/shazow.eth/0x2698e357

- [callthis.eth](https://rainbow.me/callthis.eth) (defaulting to this if people don't have strong feels)
- [transactionlink.eth](https://rainbow.me/transactionlink.eth)
- [maybecall.eth](https://rainbow.me/maybecall.eth)
- [execlink.eth](https://rainbow.me/execlink.eth)
- [runthis.eth](https://rainbow.me/runthis.eth)
- [link.contractexplorer.eth](https://rainbow.me/link.contractexplorer.eth) (under another upcoming project)
- ☎️☎️☎️☎️.eth

**Comment by shazow** [comment]
Going with callthis.eth and callthis.link

**Comment by iTzBlack007** [comment]
sendme.eth
share.eth
payments.eth

**Comment by shazow** [comment]
@iTzBlack007 None of those are available
