### ISSUE TITLE
Add Safe Support

### ISSUE THREAD

**Issue by SonOfMosiah** [shazow/callthis#21]
- [Add Safe App Provider ](https://docs.safe.global/safe-core-aa-sdk/safe-apps/overview)

- Create a manifest.json

Additional requirements here: https://docs.safe.global/safe-core-aa-sdk/safe-apps/get-started#basic-requirements

**Comment by shazow** [comment]
Great idea, thanks for tracking. Any interest in doing a PR? :)

**Comment by SonOfMosiah** [comment]
Absolutely. I'll try my hand at adding this in.

**Comment by shazow** [comment]
Fantastic! Let me know if you have any trouble getting going, I'd like to make callthis more contributor-friendly.

**Comment by shazow** [comment]
Added a manifest in https://github.com/shazow/callthis/commit/790fb9c1e6acf7740a357c8379f77c228a1206fc, pretty sure it's working now? Didn't need to do anything special for the provider.

**Comment by SonOfMosiah** [comment]
I think Safe also requires the app to "eager connect" or "auto connect" to the safe wallet.

**Comment by shazow** [comment]
@SonOfMosiah Does it not work for you rn? I think whatever I did for my custom wallet connecting happened to be compatible with what Safe does. 🙃

**Comment by SonOfMosiah** [comment]
Is the latest live on callthis.link? Wasn't able to connect through app.safe.global

**Comment by shazow** [comment]
Ah you're right, it looked like it was working but it was using the wrong wallet.

I think it's actually also a CORS issue at the moment.

**Comment by shazow** [comment]
Do you have any (working) links handy for how eager/auto connect is supposed to work? Looks like everything is 404 these days. -_-

**Comment by shazow** [comment]
Ah found it via archive.org https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-provider

**Comment by shazow** [comment]
Alright that was more annoying than I hoped but should do the trick, can you confirm when you get a chance? @SonOfMosiah

**Comment by shazow** [comment]
https://app.safe.global/share/safe-app?appUrl=http%3A%2F%2Flocalhost%3A5173&chain=eth

**Comment by shazow** [comment]
https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fcallthis.link&chain=eth
