### ISSUE TITLE
Connected wallet incorrectly always uses mainnet to getCode

### ISSUE THREAD

**Issue by shazow** [shazow/callthis#42]
To reproduce:
1. Connect wallet
2. Switch to non-mainnet address (e.g. bnb)
3. Try to load a contract (e.g. `0x001fe5d94419eae81b5436ccb7a6ecf625b7f1d3`)

Does equivalent of this call:

```js
fetch("https://ethereum-mainnet.core.chainstack.com/39f1d67cedf8b7831010a665328c9197", {
  // ...
  "body": "{\"method\":\"eth_getCode\",\"params\":[\"0x001fe5d94419eae81b5436ccb7a6ecf625b7f1d3\",\"latest\"],\"id\":2,\"jsonrpc\":\"2.0\"}",
  "method": "POST",
});
```

We shouldn't be calling ethereum-mainnet here.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by FixResolution** [comment]
[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
